# E2E method only. Superseeded by kubectl-mtb. Obsolete.

# path to cluster administrator's kubeconfig file
# Path relative to ./benchmarks/e2e/tests directory
adminKubeconfig: ../../../custom/kubeconfig-prod_cluster-admin.yml
 
# path to the tenant's kubeconfig and its namespace
# Path relative to ./benchmarks/e2e/tests directory
tenantA:
  kubeconfig: ../../../custom/kubeconfig-prod_tenant-a-prdev_tenant-admin.yml
  # kubeconfig: ../../../custom/kubeconfig_cluster-admin.yml
  namespace: tenant-a-dev
 
# path to the tenant's kubeconfig and its namespace
# Path relative to ./benchmarks/e2e/tests directory
tenantB:
  kubeconfig: ../../../custom/kubeconfig-prod_tenant-b-prdev_tenant-admin.yml
  # kubeconfig: ../../../custom/kubeconfig_cluster-admin.yml
  namespace: tenant-b-dev

# label is used to identify the resources
# managed by the cluster administrator
label:
  provider="eon.esp"
  owner="eon.esp"
